# Generated by Django 5.2.6 on 2025-09-20 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-Za-z\\-]+$', 'Тільки літери та дефіс')])),
                ('lastName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('^[A-Za-z\\-]+$', 'Тільки літери та дефіс')])),
                ('contactMethod', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=8)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Повинно бути 11 цифр')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(32), django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Тільки літери, цифри та нижнє підкреслення')])),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
