# Generated by Django 5.2.6 on 2025-09-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30, unique=True)),
                ('projDescription', models.TextField(blank=True, max_length=100, null=True)),
                ('authorName', models.CharField(blank=True, max_length=30, null=True)),
                ('projBrief', models.ImageField(blank=True, null=True, upload_to='briefs/')),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
    ]
